# -*- coding: utf-8 -*-
"""Week_5_completed

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eUTMHvzvLa-9i_PA8dc40LqlwVNYK2lG

Toshboev Utkirbek Uktam Ugli  - 23012866
"""

# section 1

equal_line = ('=' * 40)
single_line = ('-' * 40)

project = ("OpenTrack", "1.0", 2024, "Python", "Ali Hassan")

print(equal_line)
print(f"  {project[0]} — Open Source Project")
print(f"  Project lead  :  {project[0]}")
print(equal_line)

print(f"Name : {project[0]} | version : {project[1]} | started : {project[2]}")
print(f"First 3 fields : {project[0:3]}")
print(f"Language count : {project.count(project[3])}  Language index : {project.index(project[3])}")
#project[0] = 'test' # TypeError: tuple does not support item assignment.
print(" # project[0] = 'test' → TypeError: tuple does not support item assignment")

print(single_line)
contributors = []

for i in range(4):
  name = input("Name: ")
  role = input("Role: ")
  language = input("Language: ")
  commits = int(input("Commits: "))
  country = input("Country: ")

  contribut = {
      "name": name,
      "role": role,
      "language": language,
      "commits": commits,
      "country": country
  }

  contributors.append(contribut)

names = [contributor['name'] for contributor in contributors]
sorted_names = sorted(names)
print(f"\nSorted names : {sorted_names}")
print(f"Last name : {sorted_names[-1]} First two : {sorted_names[:2]}")

for contributor in contributors:
  contributor.update({"Status": "Active"})

print("Contributor 1 status :", contributors[0].get("status"))

backup = contributors[0].copy()
print("Backup : ", backup)

# section 2

issues = []

for i in range(5):
    print(f"\nEnter details for issue {i+1}:")
    iss_id = input("ID: ")
    title = input("Title: ")
    itype = input("Type (Bug/Feature): ")
    prio = input("Priority (Critical/High/Medium/Low): ")
    rep = input("Reporter: ")
    stat = input("Status (Open/In Progress/Resolved): ")
    issue = {
        "id": iss_id,
        "title": title,
        "type": itype,
        "priority": prio,
        "reporter": rep,
        "status": stat
    }
    issues.append(issue)

open_count = 0
for issue in issues:
    if issue["status"] == "Open":
        open_count += 1
print(f"\nOpen issues       : {open_count}")

issues[0]["priority"] = "Critical"
print("First issue → priority updated to Critical.")

print("Last two issues   :", issues[-2:])

print(single_line)

reporters = set()
for issue in issues:
    reporters.add(issue["reporter"])

tech_stack = set()
for contributor in contributors:
    tech_stack.add(contributor["language"])

tech_stack.add("Go")
tech_stack.discard("Ruby")

union_set = reporters.union(tech_stack)
inter_set = reporters.intersection(tech_stack)
diff_set = reporters.difference(tech_stack)

print("reporters :", reporters)
print("tech_stack :", tech_stack)
print("union :", union_set)
print("intersection :", inter_set)
print("difference :", diff_set)


priorities_set = set()
for issue in issues:
    priorities_set.add(issue["priority"])
if "Critical" in priorities_set:
    print("Critical present  : YES — flag for immediate review.")
else:
    print("Critical present  : NO")

print(single_line)

priority_count = {}
for issue in issues:
    p = issue["priority"]
    priority_count[p] = priority_count.get(p, 0) + 1


status_groups = {}
for issue in issues:
    s = issue["status"]
    if s not in status_groups:
        status_groups[s] = []
    status_groups[s].append(issue["title"])

print("priority keys :", priority_count.keys())
print("priority values :", priority_count.values())


print("Status Groups → ", end="")
first = True
for status, titles in status_groups.items():
    if not first:
        print(" | ", end="")
    print(f"{status} : {titles}", end="")
    first = False
print()

reporter_count = {}
for issue in issues:
    r = issue["reporter"]
    reporter_count[r] = reporter_count.get(r, 0) + 1

top_rep = None
top_count = 0
for r, c in reporter_count.items():
    if c > top_count:
        top_count = c
        top_rep = r
print(f"Top reporter : {top_rep} ({top_count} issues)")

issues[0].pop("type")
print("After pop('type') :", issues[0])

# section 3

import os

print("\n" + equal_line)
print("Section 3 — Save, Read and Report")
print(equal_line)

folder_name = f"{project[0][:4].lower()}_{project[0][4:].lower()}"

if not os.path.exists(folder_name):
    os.makedirs(folder_name)

print(f"Folder created : {folder_name}/")


report_path = os.path.join(folder_name, "project_report.txt")
csv_path = os.path.join(folder_name, "issues.csv")


try:
    with open(csv_path, "w", encoding="utf-8") as f:
        f.write("id,title,priority,reporter,status\n")
        for issue in issues:
            f.write(f"{issue['id']},{issue['title']},{issue['priority']},{issue['reporter']},{issue['status']}\n")


    with open(report_path, "w", encoding="utf-8") as f:
        f.write("==========================================\n")
        f.write(f"   {project[0]} — PROJECT REPORT\n")
        f.write("==========================================\n\n")
        f.write(f"Project : {project[0]} Version : {project[1]} Lead : {project[4]}\n\n")
        f.write(f"Contributors: {len(contributors)}\n")
        f.write(f"Names: {sorted_names}\n")
        f.write(f"Tech Stack: {tech_stack}\n\n")
        f.write(f"Issues: {len(issues)} | Open: {open_count}\n")
        f.write(f"Reporters: {reporters}\n")
        f.write(f"Top Reporter: {top_rep} ({top_count} issues)\n\n")
        f.write("Priority Breakdown:\n")
        for p, c in priority_count.items():
            f.write(f"- {p}: {c}\n")
        f.write("\nDetailed Issues:\n")
        for issue in issues:
            f.write(f"{issue['id']}: {issue['title']} ({issue['priority']}) - {issue['status']} by {issue['reporter']}\n")

    print("Files saved    :", os.listdir(folder_name))
except IOError as e:
    print(f"Error writing files: {e}")


try:
    print("\n--- read() ---")
    with open(report_path, "r", encoding="utf-8") as f:
        print(f.read())

    print("--- readline() ---")
    with open(report_path, "r", encoding="utf-8") as f:
        print(f"Line 1 : {f.readline().rstrip()}")
        print(f"Line 2 : {f.readline().rstrip()}")

    print("--- readlines() ---")
    with open(report_path, "r", encoding="utf-8") as f:
        lines = f.readlines()
        total_lines = len(lines)
        crit_high_lines = [line.rstrip() for line in lines if "Critical" in line or "High" in line]
        crit_high_count = len(crit_high_lines)
        print(f"Total lines : {total_lines}     Critical/High lines : {crit_high_count}")
        # print only lines containing 'Critical' or 'High'
        for line in crit_high_lines:
            print(line)
except FileNotFoundError:
    print("File not found during reading.")
except Exception as e:
    print(f"Reading error: {e}")

print(single_line)
print(equal_line)

print(f"  {project[0]} — FINAL SUMMARY \n{equal_line}")
print(f"Project : {project[0]} Version : {project[1]} lead : {project[4]} \nContributors : {len(contributors)} Names : {sorted_names} \nTech Stack : {tech_stack} \nIssues : {len(issues)} Open : {open_count} Reporters : {len(reporters)}")
print(f"Top reporter : {top_rep} ({top_count} issues)")
print(f"Priority breakdown: {' '.join(f'{p}:{v}' for p, v in priority_count.items())}")
print(f"report : {folder_name}/project_report.txt")
print(f"CSV : {folder_name}/issues.csv")
print(equal_line)
print(f"{project[0]} complete. Thank you for contributing to open source!")
print(equal_line)

# Part 1
urgent = [issue["title"] for issue in issues if issue["priority"] in ("Critical", "High")]
print("Urgent issues :", urgent)
print("Number of urgent issues :", len(urgent))

# Part 2:
try:
    with open(report_path, "a", encoding="utf-8") as f:
        f.write("\n\nURGENT ISSUES\n")
        f.write("=============\n")
        for title in urgent:
            f.write(f"- {title}\n")

    with open(report_path, "r", encoding="utf-8") as f:
        lines = f.readlines()
    print("\nLast 6 lines after append (confirming URGENT section):")
    for line in lines[-6:]:
        print(line.rstrip())
except Exception as e:
    print(f"Append error: {e}")

print(single_line)

print(f"{project[0]} — FINAL SUMMARY \n{equal_line}")
print(f"Project : {project[0]} Version : {project[1]} Lead : {project[4]} contributors : {len(contributors)} \nNames : {sorted_names} \nTech Stack : {tech_stack} \nIssues : {len(issues)} Open : {open_count} Reporters : {len(reporters)}")
print(f"Top Reporter : {top_rep} ({top_count} issues)")
print(f"Priority breakdown: {' '.join(f'{p}:{v}' for p, v in priority_count.items())}")
print(f"Report : {folder_name}/project_report.txt")
print(f"CSV : {folder_name}/issues.csv")
print(equal_line)
print(f"{project[0]} complete. Thank you for contributing to open source!")
print(equal_line)

